I'm sorry, but an uncaught exception occurred.

After initialization, but before game start.
  File "game/screens.rpy", line 590, in prepare_screen
    screen save():
  File "game/screens.rpy", line 590, in prepare
    screen save():
Exception: A screen named file_slots does not exist.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "C:\Users\Tatiana Krupenina\Desktop\Renpy\renpy-7.3.5-sdk\renpy\bootstrap.py", line 316, in bootstrap
    renpy.main.main()
  File "C:\Users\Tatiana Krupenina\Desktop\Renpy\renpy-7.3.5-sdk\renpy\main.py", line 578, in main
    run(restart)
  File "C:\Users\Tatiana Krupenina\Desktop\Renpy\renpy-7.3.5-sdk\renpy\main.py", line 94, in run
    renpy.display.screen.prepare_screens()
  File "C:\Users\Tatiana Krupenina\Desktop\Renpy\renpy-7.3.5-sdk\renpy\display\screen.py", line 931, in prepare_screens
    s.ast.prepare_screen()
  File "game/screens.rpy", line 590, in prepare_screen
    screen save():
  File "game/screens.rpy", line 590, in prepare
    screen save():
  File "C:\Users\Tatiana Krupenina\Desktop\Renpy\renpy-7.3.5-sdk\renpy\sl2\slast.py", line 1719, in prepare
    raise Exception("A screen named {} does not exist.".format(self.target))
Exception: A screen named file_slots does not exist.

Windows-8-6.2.9200
Ren'Py 7.3.5.606
Vanitas 1.0
Tue Jun 30 23:32:25 2020
